[package]
name = "pic24e"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sleigh2macro = { path = "../../sleigh2macro", version = "0.1.5" }

