[package]
name = "dylib_80390"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethnum = "1"
sleigh4rust = { "path" = "../../sleigh4rust"}

[lib]
crate-type = ["dylib"]
